name: My First Workflow

run-name: ${{ github.actor }} is learning GitHub Actions


on: 
 push:
 workflow_dispatch:

jobs:
  echo-print:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        maven: [ '3.8.8', '3.9.8' ]

        name: Maven ${{ matrix.maven }} sample

   steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Setup Maven Action
        uses: aahmed-se/setup-maven@v3
        with:
          java-version: '17'
          maven-version: ${{ matrix.maven }}

      - run: mvn -V 
          
     
    
