name: My First Workflow

run-name: ${{ github.actor }} is learning GitHub Actions


on: 
 push:
 workflow_dispatch:

jobs:
  echo-print:
   runs-on: ubuntu-latest
   steps:  
    - run: echo "This is my First Workflow"
    - name: Setup Java JDK
    - uses: actions/setup-java@v1
      with: 
         java-version: '11'
    
