name: My First Workflow

run-name: ${{ github.actor }} is learning GitHub Actions


on: 
 push:
 workflow_dispatch:

jobs:
  echo-print:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        maven: [ '3.8.8', '3.9.8' ]

        

   steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
           maven-version: 3.8.2
      - run: mvn -V 
          
     
    
