name: My First Workflow

run-name: ${{ github.actor }} is learning GitHub Actions


on: 
 push:
 workflow_dispatch:

jobs:
  echo-print:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: action-maven

        uses: comchangs/action-maven@v0.4-beta
          
     
    
