name: Workflow for Running in Diff OS

on: 
 push

jobs:
 run-on-ubuntu-machine:
  runs-on: ubuntu-latest
  steps:
   - run: echo "It is running on $RUNNER_OS" 
 run-on-windows:
  runs-on: windows-latest
  steps:
      - name: Shell 
        shell: bash
        run: echo "Runner OS is $RUNNER_OS"
