name: Conetxt for env
on:
 push:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false
env:                                             # add this line alone
 MY_WORKFLOW_VAR: "workflow"                     # add this line alone
 MY_OVERWRITTEN_VAR: "workflow"                  # add this line alone
jobs:
 echo-data:
  runs-on: ubuntu-latest
  env:                        
    MY_WORKFLOW_VAR: "job"     
    MY_OVERWRITTEN_VAR: "job"
  steps:
   - name: Display Info
     env:
        MY_WORKFLOW_VAR: "step"           # add this line alone
        MY_OVERWRITTEN_VAR: "step"    
     run: |
      echo "Event name ${{github.event_name}}"
      echo "Ref: ${{github.ref}}"
      echo "SHA: ${{github.sha}}"
      echo "Actor: ${{github.actor}}"
      echo "Workflow: ${{github.workflow}}"
      echo "Run Id: ${{github.run_id}}"
      echo "Run number: ${{github.run_number}}"
      echo "Env variable is: ${{var.MY_VAR}}"
      echo  "ENV variable is: ${{env.MY_OVERWRITTEN_VAR}}"
