name: Reusable Workflow

on:
 workflow_call:
  inputs:
   message: 
   description: Message to print
   required: true
   type: string
jobs:
 print-meesage:
 runs-on: ubuntu-latest
 steps: 
  - name: Print Message
    run: echo ${{inputs.message}}"
 
