name: simple api key with secrets

on:
 push:
jobs:
 api-secrets:
  runs-on: ubuntu-latest
  steps:
   - name:  Authentication
     env:
      API_KEY: ${{secrets.API_KEY}}
      run: |
       echo: "Authorisation: $API_KEY"
  
