name: Simple API Request1

on:
 push:

jobs:
 call-api:
  runs-on: ubuntu-latest

  steps:
   - name: Make a auntenticated API request
     env:
      API_KEY: ${{ secrets.API_KEY}}
     run: |
      echo "Authorization: Bearer $API_KEY"
